[package]
name = "pc-auth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
pc-core.workspace = true
pc-http.workspace = true
pc-redis.workspace = true
pc-snapbi.workspace = true
pc-validate.workspace = true
axum.workspace = true
md-5.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
tracing.workspace = true
